NEWEBODAC-27: Create user role management page
motech-implementations/new-ebodac pull request #33
Opened 2019-09-20 08:52 UTC by mariaogryczak

For now, could you just check what is wrong with connecting the components, that the added role does not appear on the role list?

2019-09-23 14:25 UTC, pmuchowski requested changes

2019-09-23 14:25 UTC, pmuchowski commented on src/main/webapp/js/actions/types.js
> +export const FETCH_VACCINEE_CONFIG = 'fetch_vaccinee_config';
remove all of those types, there are not use anywhere

2019-09-23 14:25 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/constants/DefaultPermissions.java
> +  public static final String INCHARGE_READ = "ROLE_INCHARGE_READ";
there are no incharges in this project, remove all unused permissions

2019-09-23 14:25 UTC, pmuchowski commented on src/main/webapp/js/reducers/entity-reducer.js
> +        role: action.payload.data,
the entityType will be 'role' in this case, so remove this

2019-09-23 14:25 UTC, pmuchowski commented on src/main/webapp/js/reducers/field-config-reducer.js
> +  role: {},
the field config for roles and permissions is not fetched from the backend, but it's a constant, so remove this

2019-09-23 14:25 UTC, pmuchowski commented on src/main/webapp/js/components/navbar.jsx
> +                    <RoutePrivate path="/roleFields" component={RoleFields} />
the field config for roles is not editable, so remove this

2019-09-23 14:25 UTC, pmuchowski commented on src/main/webapp/js/components/sidebar.jsx
> +        <li className="border-none">
remove this, the field roles field config is not editable

2019-09-23 14:25 UTC, pmuchowski commented on src/main/webapp/js/components/fields/role-fields.jsx
> +const RoleFields = () => (
remove this, role field config is not editable

2019-09-23 14:25 UTC, pmuchowski commented on src/main/webapp/css/main.scss
> +.role-buttons {
are those classes used anywhere, if not remove it

2019-09-23 14:25 UTC, pmuchowski commented on src/main/webapp/js/utils/entity-types.js
> +export const ROLE_ENTITY = 'role';
you will need to add entity for the permission too

2019-09-23 14:25 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/web/RoleController.java
> +  }
you will need to add a separate endpoint to fetch all permissions

2019-09-23 14:25 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/web/RoleController.java
> +  @RequestMapping(value = "/role/create", method = RequestMethod.POST)
remove '/create' from the url

2019-09-23 14:25 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/web/RoleController.java
> +  @RequestMapping(value = "/role/delete", method = RequestMethod.DELETE)
remove '/delete' from the url

2019-09-23 14:25 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/service/RoleService.java
> +  private PermissionRepository permissionRepository;
you will need to add `@Autowired` on this field too

2019-09-23 14:25 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/service/RoleService.java
> +  public RoleDto updateFromDto(UUID id, RoleDto roleDto) {
rename this to 'update'

2019-09-23 14:25 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/mapper/RoleMapper.java
> +  RoleDto toDto(UserRole role);
if you're not changing any mappers, you don't need to implement this (there is default implementation in EntityMapper), so remove it

2019-09-23 14:25 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/mapper/RoleMapper.java
> +  @Mappings({
there is not need for this, this was removed in newer versions of mapstruct

2019-09-23 14:25 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/mapper/RoleMapper.java
> +  @Mappings({
as above

2019-09-23 14:25 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/mapper/RoleMapper.java
> +  List<RoleDto> toDtos(Iterable<UserRole> role);
you can remove it

2019-09-23 14:25 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/dto/RoleDto.java
> +  private String roleId;
rename this to id

2019-09-27 08:29 UTC, mariaogryczak commented
@pmuchowski 
Could you check what I did so far?
Could you give me any suggestion how to connect Role Entity with Permission Entity (I suppose I need to use relatedEntity field)? And how to connect Default Permissions with all of this?

2019-09-27 10:26 UTC, pmuchowski requested changes

2019-09-27 10:26 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/mapper/RoleMapper.java
> +  void update(RoleDto roleDto, @MappingTarget UserRole role);
add ignore for id, createDate, updateDate and readonly fields

2019-09-27 10:26 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/web/RoleController.java
> +  @RequestMapping(value = "/role/permission", method = RequestMethod.GET)
change the url to '/permission'

2019-09-27 10:26 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/dto/RoleDto.java
> +public class RoleDto {
it should extend the BaseDto

2019-09-27 10:26 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/dto/PermissionDto.java
> +public class PermissionDto {
it should extend the BaseDto

2019-09-27 10:26 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/dto/RoleDto.java
> +  private Set<ExtraFieldDto> extraFields;
remove this

2019-09-27 10:26 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/dto/RoleDto.java
> +  private Set<PermissionDto> permissions = new HashSet<>();
change it to `Set<UUID>` and store only ids of permissions here

2019-09-27 10:26 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/domain/security/UserRole.java
> -  @NotBlank
you should not remove this

2019-09-27 10:26 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/mapper/RoleMapper.java
> +
you will need to add new methods here to map UUID to UserPermission and other way around

2019-09-30 10:44 UTC, pmuchowski requested changes

2019-09-30 10:44 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/mapper/RoleMapper.java
> +    return new UserPermission();
you need to set the id for the UserPermission, also add another method to map UserPermission to UUID

2019-09-30 10:44 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/mapper/PermissionMapper.java
> +@Mapper(uses = { UuidMapper.class },
remove the UuidMapper

2019-09-30 10:44 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/mapper/PermissionMapper.java
> +  List<PermissionDto> toDtos(Iterable<UserPermission> id);
rename the argument, it should be permissions or something similar, not id

2019-09-30 10:44 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/mapper/RoleMapper.java
> +@Mapper(uses = { UuidMapper.class },
remove the UuidMapper

2019-09-30 10:44 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/dto/RoleDto.java
> +  private Set<UUID> permissionId = new HashSet<>();
this should be named permissionIds

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/fields/field-config-modal.jsx
> +export const defaultConfig = {
it's not used anywhere, so remove the export

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/selectors/index.js
> +export const getFieldConfigByEntity = (state, { entityType }) => state.fieldConfig[entityType];
it's not used anywhere, so remove the export

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +          relatedEntity={PERMISSION_ENTITY}
remove this, relatedEntity is not one of the EntityTable properties

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  componentDidMount() {
you need to fetch the user roles and permissions here, you can use 'fetchEntity' for this

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  base: false,
all of those fields are base fields

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  editable: true,
id is not editable

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  hidden: false,
id should be hidden

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  fieldType: null,
field type cannot be null, change it to TEXT

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  fieldType: null,
field type cannot be null, change it to TEXT

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  entity: null,
entity is ROLE_ENTITY

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  relatedEntity: PERMISSION_ENTITY,
this should be null

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  entity: null,
entity is ROLE_ENTITY

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  entity: null,
entity is ROLE_ENTITY

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  required: false,
name is required

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  relatedEntity: PERMISSION_ENTITY,
this should be null

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  name: 'user_role_permissions',
name should be permissionIds

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  relatedField: null,
the related field should be 'displayName'

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  fieldType: null,
field type is 'COLLECTION'

2019-09-30 10:44 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +export const defaultRoleConfig = [{
rename this to roleFieldConfig and create a new file named 'field-configs.js' (in utils) and move this config there

2019-09-30 10:44 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/constants/DefaultPermissions.java
> +  public static final String HAS_GROUP_READ_OR_VACCINEE_WRITE =
are you using this anywhere?

2019-10-02 12:49 UTC, pmuchowski requested changes

2019-10-02 12:49 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/mapper/RoleMapper.java
> +  default Set<UserPermission> toUserPermission(UUID id) {
this should not be a Set, just one UserPermission, return `new UserPermission(id)` here

2019-10-02 12:49 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/mapper/RoleMapper.java
> +  default Set<UUID> toUuid(UserPermission id) {
change the parameter name to userPermission and return UserPermission id here (single id not Set of ids)

2019-10-02 12:49 UTC, pmuchowski commented on src/main/webapp/js/components/navbar.jsx
> +                    <RoutePrivate path="/entityEdit/role/:id" component={RoleEditPage} />
it's fine, but would be better if you used ROLE_ENTITY const here

2019-10-02 12:49 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +  history: PropTypes.shape({
you don't need the history prop here

2019-10-02 12:49 UTC, pmuchowski commented on src/main/webapp/js/components/user-managment/roles.jsx
> +    this.props.fetchEntity(ROLE_ENTITY);
actually role entity will be fetched in EntityTable component, so you can remove this, just fetch the permissions

2019-10-02 12:49 UTC, pmuchowski commented on src/main/webapp/js/utils/table-cells/collection-cell.jsx
> +  const collectionCellValue = JSON.stringify(entityArray[0][relatedField]);
I think you should create a selector to get the list of values.
In this component use `_.join(values, ', ')` to display the values

2019-10-02 13:23 UTC, pmuchowski requested changes

2019-10-02 13:23 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/domain/security/UserPermission.java
> +public static UUID id;
remove this

2019-10-02 13:23 UTC, pmuchowski commented on src/main/java/org/motechproject/newebodac/mapper/RoleMapper.java
> +    return UserPermission.id;
use `userPermission.getId()`

2019-10-02 13:23 UTC, pmuchowski commented on src/main/webapp/js/components/navbar.jsx
> +import ROLE_ENTITY from '../utils/entity-types';
it's not default export, it will not work like this, add it in `{}`

2019-10-03 08:52 UTC, merged